# Generated by Django 4.0.6 on 2022-08-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text="Determine if the User's email has been confirmed.", verbose_name='email confirmed?'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='image',
            field=models.ImageField(blank=True, upload_to='viewer/images'),
        ),
    ]
