# Generated by Django 4.1 on 2022-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_creator_school_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
    ]
