# Generated by Django 4.1 on 2022-08-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_like_count_video_likes_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
