# Generated by Django 4.1 on 2022-08-13 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_remove_video_like_count_remove_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='favorites',
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who added video to their likes.', related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user likes'),
        ),
    ]
