# Generated by Django 4.1 on 2022-08-15 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0006_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AddField(
            model_name='video',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Users who added video to their favorites.', related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='user favorites'),
        ),
    ]
