# Generated by Django 4.1 on 2022-08-15 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0007_remove_video_like_count_remove_video_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='users_favorites',
            field=models.ManyToManyField(blank=True, help_text='Users who added video to their favorites.', related_name='videos_favorites', to=settings.AUTH_USER_MODEL, verbose_name='users favorites'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='favorites',
        ),
        migrations.AddField(
            model_name='video',
            name='favorites',
            field=models.BigIntegerField(default=0),
        ),
    ]
